version: '2'

services:

  startup:
    depends_on:
      - zookeeper
      - kafka
      - arangodb
    build: ./startup
    container_name: startup
    ports: 
      - "80"
    volumes:
      - ./startup:/code/startup
    environment:
      - NODE_ENV=development

  # proxy routes OAuth2 requests (/auth, /code) to auth service,
  # and the rest to main http-handlers.  TODO: add load balancing with multiple handlers.
  proxy:
    depends_on: 
      - auth
      - http-handler
      - well-known
    build: ./proxy
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/dev-sites-enabled/:/etc/nginx/sites-enabled/
      - ./proxy/dev-certs/:/certs/
      - ./proxy:/code/proxy
    environment:
      - NODE_ENV=development
    command:
      - /entrypoint.sh

  auth:
    depends_on:
      - startup
    build: ./auth
    container_name: auth
    restart: always
    ports:
      - "80"
    volumes:
      - ./auth:/code/auth
    environment:
      - NODE_ENV=development
    command:
      - /entrypoint.sh

  # http-handler is in charge of maintaining connectiongs to clients and starting
  # the first message for a request into Kafka
  http-handler:
    depends_on:
      - startup
    build: ./http-handler
    container_name: http-handler
    ports:
      - "80"
    volumes:
      - ./http-handler:/code/http-handler
    environment:
      - NODE_ENV="development"

  token-lookup:
    depends_on:
      - startup
    build: ./token-lookup
    container_name: token-lookup
    volumes:
      - ./token-lookup:/code/token-lookup
    environment:
      - NODE_ENV="development"

  graph-lookup:
    depends_on:
      - startup
    build: ./graph-lookup
    container_name: graph-lookup
    volumes:
      - ./graph-lookup:/code/graph-lookup
    environment:
      - NODE_ENV="development"

  well-known:
    depends_on:
      - startup
    build: ./well-known
    container_name: well-known
    volumes:
      - ./well-known:/code/well-known
    ports:
      - "80"
    environment:
      - NODE_ENV="development"

  tests:
    depends_on:
      - startup
    build: ./tests
    container_name: tests
    volumes:
      - ./tests:/code/tests
    environment:
      - NODE_ENV="development"

  # Arango is the main backend where core data and graph is stored
  arangodb:
    image: arangodb
    container_name: arangodb
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_data:/var/lib/arangodb3-apps
    ports:
      - "8529:8529"
    environment:
      # - ARANGO_RANDOM_ROOT_PASSWORD=1
      - ARANGO_NO_AUTH=1

  # admin container has all the service names and volumes mapped, so you
  # can interact with them easily from this service.
  admin:
    build: ./admin
    volumes:
      - arangodb_data:/volumes/arangodb
      - arangodb_apps_data:/volumes/arangodb_apps
      - zookeeper_data:/volumes/zookeeper
      - kafka_data:/volumes/kafka
      - ./auth:/code/auth
      - ./example:/code/example
      - ./graph-lookup:/code/graph-lookup
      - ./token-lookup:/code/token-lookup
      - ./http-handler:/code/http-handler
      - ./well-known:/code/well-known
      - ./tests:/code/tests
      - ./admin:/code/admin
      - ./startup:/code/startup
      - ./oada-lib-arangodb:/code/oada-lib-arangodb
    command: bash


  # zookeeper and kafka entries are based on:
  # from https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose.yml
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"  # NOTE: this only allows services inside this docker network
      KAFKA_ADVERTISED_PORT: "9092"        # to connect to kafka.  Set to machine's IP if you want external.
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/var/lib/kafka

volumes:
  arangodb_data:
  arangodb_apps_data:
  kafka_data:
  zookeeper_data:
